# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Default command to run the MCP server
CMD ["python", "-m", "server"]
